### ISSUE TITLE
Order of inserts

### ISSUE THREAD

**Issue by felix** [eltiare/dm-is-awesome_set#1]
When creating a new 'root' the order is different to when an object is inserted _into_ a root.

**Comment by eltiare** [comment]
I have no idea to what you are inferring. Some examples of what is happening vs what you expect to happen would be nice.

**Comment by felix** [comment]
My apologies, I can't remember even posting that. Looking back at my code, it seems that on creating a new item in a set that has _no parent_, the resulting order of its siblings is different to the order of siblings that are created _with_ a parent. So,

```
one   = Foo.create({:name => 'one'})
two   = Foo.create({:name => 'two'})
three = Foo.create({:name => 'three'})
four  = Foo.create({:name => 'four'})
five  = Foo.create({:name => 'five'})
six   = Foo.create({:name => 'six'})

four.move(:into => one)
five.move(:into => one)
six.move(:into  => one)
```

results in:

```
.
|-- one
|   |-- six
|   |-- five
|   `-- four
|--two
`--three
```

To me it seems 'one's children should be reversed, each child being _appended_ rather than _prepended_, as the parentless nodes are.

Not a big issue, obviously, and it could be by design. But that is what I was getting at.

**Comment by eltiare** [comment]
Curious. I will look into it, I think you are right that nodes should be appended.
